name: Wiki-To-PDF-$(Rev:rr)
trigger: none

stages:
- stage: wiki_export
  displayName: Wiki Export

  jobs:
  - job: wiki_to_pdf
    displayName: Wiki To PDF
    pool:
      vmImage: windows-latest
    
    steps:
    - task: richardfennellBM.BM-VSTS-WikiPDFExport-Tasks.WikiPDFExportTask.WikiPdfExportTask@1
      displayName: 'Export a private Azure DevOps WIKI'
      inputs:
        cloneRepo: true
        repo: 'https://dev.azure.com/magiconionM/Devto_Blog_Demos/_git/DevOps.Wiki'
        useAgentToken: true
        localpath: '$(System.DefaultWorkingDirectory)/DevOpsWiki' 
        outputFile: '$(Build.ArtifactStagingDirectory)/PDF/DevOpsWiki.pdf'
    
    - task: PublishPipelineArtifact@1
      displayName: 'Publish wiki export to Azure Pipeline'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/PDF'
        artifactName: DevOpsWiki

