name: Deployment-Prod-RG-$(Rev:rr)
trigger: none

variables:
- template: variables/common_vars.yml
- template: variables/prod_vars.yml

stages:
- stage: TF_DEPLOY_PROD_RG
  displayName: Deploy Prod ResourceGroup
  dependsOn: []
  jobs:
    - deployment: TF_Deploy_Prod_Rg
      displayName: Terraform - Prod - RG
      pool:
        name: Azure Pipelines
        vmImage: windows-latest
      workspace:
        clean: all
      environment: Infra-Prod
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              ### Run common terraform deploy steps
              - template: task_groups/tf_deploy_tasks.yml
                parameters:
                  terraformVersion: ${{ variables.terraformVersion }}
                  rootDirName: ${{ variables.rootDirName }}
                  AzureServiceConnection: ${{ variables.AzureServiceConnection }}
                  terraformBackendRG: ${{ variables.terraformBackendRG }}
                  terraformBackendSA: ${{ variables.terraformBackendSA }}