name: Deployment-Dev-RG-$(Rev:rr)
trigger: none

variables:
- template: variables/common_vars.yml
- template: variables/dev_vars.yml

stages:
- stage: TF_DEPLOY_DEV_RG
  displayName: Deploy Dev ResourceGroup
  dependsOn: []
  jobs:
    - deployment: TF_Deploy_Dev_Rg
      displayName: Terraform - Dev - RG
      pool:
        name: Azure Pipelines
        vmImage: windows-latest
      workspace:
        clean: all
      environment: Infra-Dev
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              ### Run common terraform deploy steps
              - template: task_groups/tf_deploy_tasks.yml
                parameters:
                  terraformVersion: ${{ variables.terraformVersion }}
                  rootDirName: ${{ variables.rootDirName }}
                  AzureServiceConnection: ${{ variables.AzureServiceConnection }}
                  terraformBackendRG: ${{ variables.terraformBackendRG }}
                  terraformBackendSA: ${{ variables.terraformBackendSA }}
                  environment: ${{ variables.environment }}
