
name: Check Markdown files on Dev Branch
# This workflow checks for changes in Markdown files on the dev branch and runs linting and formatting tools.
# It does not publish to Dev.to. The publish step is handled in the main workflow.
# It is triggered on push events to the dev branch.

on:
  push:
    branches:
      - dev
    paths:
      - 'posts/**/**.md'
      - 'posts/**/**/**.md'

jobs:
  CheckMarkdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Check Changed Files
        uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          files: |
            posts/**/**/**.md
            posts/**/**.md 
          separator: ","

      - name: Lint Markdown files
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: ${{ steps.changed-files.outputs.all_changed_files }}
          separator: ","
          config: ./.github/.markdownlint.json

      - name: Dry Run Publish to Dev.to
        uses: sinedied/publish-devto@v2
        with:
          files: 'posts/**/*.md'
          devto_key: ${{ secrets.DEVTO_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
